import type { Config } from "tailwindcss";

// Tokens transcritos literalmente del `tailwind.config` embebido en los
// mockups de Stitch (stitch_art_ex_menes_m_dicos_peri_dicos/*/code.html),
// que es la fuente real de los estilos que se ven en los screen.png.
export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#074d5f",
        "secondary-fixed-dim": "#63d6e8",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bec8cd",
        error: "#ba1a1a",
        "on-background": "#111c2d",
        "tertiary-fixed": "#b6eaff",
        "on-error": "#ffffff",
        "surface-dim": "#cfdaf2",
        "primary-container": "#007693",
        "surface-bright": "#f9f9ff",
        "on-primary-container": "#daf3ff",
        tertiary: "#1e5b6e",
        "on-primary-fixed-variant": "#004d61",
        "on-tertiary-container": "#daf4ff",
        "primary-fixed-dim": "#7dd2f2",
        "on-primary-fixed": "#001f29",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-container": "#7cedff",
        "surface-variant": "#d8e3fb",
        "inverse-on-surface": "#ecf1ff",
        primary: "#005c73",
        outline: "#6f797d",
        "on-secondary-container": "#006b77",
        "tertiary-fixed-dim": "#97cfe4",
        "surface-container-low": "#f0f3ff",
        "primary-fixed": "#b9eaff",
        "surface-container-high": "#dee8ff",
        background: "#f9f9ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#263143",
        "inverse-primary": "#7dd2f2",
        "error-container": "#ffdad6",
        "surface-container": "#e7eeff",
        "on-surface-variant": "#3f484d",
        "tertiary-container": "#3b7487",
        "on-tertiary-fixed": "#001f28",
        secondary: "#006874",
        "on-surface": "#111c2d",
        "on-secondary-fixed": "#001f24",
        surface: "#f9f9ff",
        "surface-container-highest": "#d8e3fb",
        "on-secondary-fixed-variant": "#004f58",
        "surface-tint": "#006781",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#98f0ff",
        // Semánticos, no presentes en el config de los mockups (screen 4
        // usa hex hardcodeado para el estado "en curso"); se normalizan acá.
        warning: "#d97706",
        "warning-container": "#fef3c7",
        "on-warning-container": "#92400e",
        success: "#16a34a",
        "success-container": "#dcfce7",
        "on-success-container": "#166534",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.75rem",
        "gutter-mobile": "1rem",
        "space-xl": "1.5rem",
        "space-3xl": "2.5rem",
        "space-xs": "0.5rem",
        "space-2xl": "2rem",
        "space-md": "1rem",
        "touch-target-min": "3rem",
        "space-lg": "1.25rem",
        "space-2xs": "0.25rem",
        "margin-screen": "1rem",
      },
      fontFamily: {
        "headline-md": ["Rubik"],
        "headline-sm": ["Rubik"],
        display: ["Rubik"],
        "body-sm": ["Rubik"],
        "headline-lg": ["Rubik"],
        title: ["Rubik"],
        "body-lg": ["Rubik"],
        "body-md": ["Rubik"],
        "label-md": ["Rubik"],
        "label-lg": ["Rubik"],
        "label-sm": ["Rubik"],
      },
      fontSize: {
        "headline-md": [
          "22px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" },
        ],
        display: [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "headline-lg": [
          "26px",
          { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        title: [
          "16px",
          { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "label-sm": [
          "10px",
          { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
      },
      boxShadow: {
        card: "0px 2px 8px rgba(0, 37, 46, 0.05)",
        modal: "0px 8px 24px rgba(0, 37, 46, 0.12)",
        pressed: "0px 1px 2px rgba(0, 37, 46, 0.08)",
      },
    },
  },
  plugins: [],
} satisfies Config;
